<?php

namespace Magenest\LoadingScreen\Block;

class Ajax extends \Magento\Framework\View\Element\Template
{
    public function toHtml()
    {
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
}